### ISSUE TITLE
Add keys for channels to the config file

### ISSUE THREAD

**Issue by limoragni** [Aluxian/squirrel-updates-server#6]
I think it would be great if the keys associated to each channel could be configured.

Now its considering a development version anything with the keys `beta` or `dev`. In my workflow I would like to use a `-` instead of those keys. Let me know it this is something you would like to add. Also I would be glad to help!

**Comment by Aluxian** [comment]
Of course, the `[stable, beta, dev]` array can be moved to the config file, together with a `defaultChannel` field. I'll accept a PR if you're willing to add this.

Some decisions were made to fit my own use case, that's why those channels are hard coded. But I'm happy to make it more general to fit more use cases/workflows.

I don't understand your use case, though. Why would you want to use `-`? Why don't you just use the route without a channel (although you'd have to make a few changes)?

**Comment by limoragni** [comment]
Well, I like to use npm versioning. I'm also using electron-builder. So the version in the package.json would turn into the name of the release. In npm you have some convenient methods like `npm version patch` or `npm version prerelease` when I use prerelease the version 1.0.1 turns into 1.0.1-0. I want the pre-releases (those that have a `-` in the name) to be on the dev channel, so it only updates the dev versions. I'm just starting to thin about this, so it was just an example. I'm also considering other solutions. At the end I want to automate all the realising process as much as I can.

**Comment by limoragni** [comment]
With this in mind, maybe it would also be helpful to not include releases marked as pre-release in the stable channel. What do you think?

**Comment by Aluxian** [comment]
If you want to treat versions with a `-` as `dev` releases, I think you should fork the project because that's a very specific use case.

If you want to exclude prereleases from a channel, I think this can be done with an option in config.
